src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $name;
    
    /**
     * @ORM\Column(type="string", length=60)
     */
    private $surname;

    /**
     * @ORM\Column(type="datetime")
     */
    private $from_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $to_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $locator;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_people;

    /**
     * @ORM\Column(type="float")
     */
    private $total_cost;

    /**
     * @ORM\Column(type="string", length=12)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $credict_card_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $extra_notes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\RoomType", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $room_type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFromDate(): ?\DateTimeInterface
    {
        return $this->from_date;
    }

    public function setFromDate(\DateTimeInterface $from_date): self
    {
        $this->from_date = $from_date;

        return $this;
    }

    public function getToDate(): ?\DateTimeInterface
    {
        return $this->to_date;
    }

    public function setToDate(\DateTimeInterface $to_date): self
    {
        $this->to_date = $to_date;

        return $this;
    }

    public function getLocator(): ?string
    {
        return $this->locator;
    }

    public function setLocator(string $locator): self
    {
        $this->locator = $locator;

        return $this;
    }

    public function getNumPeople(): ?int
    {
        return $this->num_people;
    }

    public function setNumPeople(int $num_people): self
    {
        $this->num_people = $num_people;

        return $this;
    }

    public function getRoomTypeId(): ?int
    {
        return $this->room_type_id;
    }

    public function setRoomTypeId(int $room_type_id): self
    {
        $this->room_type_id = $room_type_id;

        return $this;
    }

    public function getTotalCost(): ?float
    {
        return $this->total_cost;
    }

    public function setTotalCost(float $total_cost): self
    {
        $this->total_cost = $total_cost;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCredictCardNumber(): ?string
    {
        return $this->credict_card_number;
    }

    public function setCredictCardNumber(string $credict_card_number): self
    {
        $this->credict_card_number = $credict_card_number;

        return $this;
    }

    public function getExtraNotes(): ?string
    {
        return $this->extra_notes;
    }

    public function setExtraNotes(?string $extra_notes): self
    {
        $this->extra_notes = $extra_notes;

        return $this;
    }

    public function getRoomType(): ?RoomType
    {
        return $this->room_type;
    }

    public function setRoomType(?RoomType $room_type): self
    {
        $this->room_type = $room_type;

        return $this;
    }

    public function getNumDays(): ?int
    {
        return date_diff($this->from_date,$this->to_date)->days + 1;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Array
     * Convierte en array el elemento
     */
    public function toArray()
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'surname' => $this->surname,
            'email' => $this->email,
            'locator' => $this->locator,
            'num_people' => $this->num_people,
            'total_cost' => $this->total_cost,
            'total_cost_formated' => number_format($this->total_cost,2,',','.'),
            'from_date' => $this->from_date->format('Y-m-d'),
            'to_date' => $this->to_date->format('Y-m-d'),
            'phone' => $this->phone,
            'extra_notes' => $this->extra_notes,
            'room_type' => $this->room_type->toArray()
        ];
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %} - Symfotel</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
            <h5 class="my-0 mr-md-auto font-weight-normal"><a href="/">Symfotel</a></h5>
            <nav class="my-2 my-md-0 mr-md-3">
                <a href="/dashboard">Dashboard</a>
            </nav>
            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                <b>{{ app.user.name }}</b> <a href="/logout">(Logout)</a>
            {% else %}
                <a href="/login">Login</a>
            {% endif %}
        </div>
        {% include "errors.html.twig" %}
        {% block body %}{% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            <script src="https://cdn.jsdelivr.net/npm/vue@2.6.7/dist/vue.js"></script>
            <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        {% endblock %}
    </body>
</html>

templates/booking_success.html.twig
{% extends "base.html.twig" %}
{% block title %}Reserva confirmada{% endblock %}

{% block body %}
    <div class="container" id="app">
        <div class="row">
            <div class="col-12 my-3">
                <div class="alert alert-success">
                    <h3>¡Reserva confirmada!</h3>
                    <h4>Aquí tienes los datos de tu reserva:</h4>
                </div>
            </div>
            <div class="col-12 my-3">
                <div class="alert alert-info">
                    <h5><i class="fas fa-dot-circle"></i> Desde el {{booking.getFromDate|date("d/m/Y")}} hasta el {{booking.getToDate|date("d/m/Y")}} ({{booking.getNumDays}} Día/s)</h5>
                    <h5><i class="fas fa-dot-circle"></i> {{booking.getNumPeople}} Personas</h5>
                    <h5><i class="fas fa-dot-circle"></i> Tipo de habitación: {{booking.getRoomType.getName}}</h5>
                    <h5><i class="fas fa-dot-circle"></i> Localizador: {{booking.getLocator}}</h5>
                    <h5><i class="fas fa-dot-circle"></i> Nº Tarjeta de crédito: {{booking.getCredictCardNumber}}</h5>
                    {% if booking.extraNotes %}
                    <h5><i class="fas fa-dot-circle"></i> Notas adicionales: {{booking.extraNotes}}</h5>
                    {% endif %}
                    <h5><i class="fas fa-dot-circle"></i> Importe total: {{booking.totalCost|number_format(2,',','.')}}€</h5>
                </div>
            </div>
            <div class="col-12 my-3">
                <a href="/login">Logueate para gestionar tus reservas</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/errors.html.twig
<div class="container">
    <div class="row">
        <div class="col-12">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                {% if label == 'error' %}
                    <div class="alert alert-danger">
                {% else %}
                    <div class="alert alert-success">
                {% endif %}
                        {{ message }}
                    </div>
            {% endfor %}
        {% endfor %}
        </div>
    </div>
</div>

templates/home.html.twig
{% extends "base.html.twig" %}
{% block title %}Home{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>¡Tus habitaciones al mejor precio!</h1>
            </div>
            <div class="col-12">
                <div class="alert alert-warning">
                    <form action="{{ url("search") }}" method="GET">
                        <div class="row">
                            <div class="col-12 col-md-4">
                                <div class="form-group">
                                    <label for="">Desde</label>
                                    <input type="date" name="from_date" class="form-control">
                                </div>
                            </div>
                            <div class="col-12 col-md-4">
                                <div class="form-group">
                                    <label for="">Hasta</label>
                                    <input type="date" name="to_date" class="form-control">
                                </div>
                            </div>
                            <div class="col-12 col-md-4">
                                <div class="form-group">
                                    <label for="">Nº de huéspedes</label>
                                    <input name="num_persons" class="form-control" type="number" min="1" value="2">
                                </div>
                            </div>
                            <div class="col-12 col-md-6 offset-md-3">
                                <input class="btn btn-primary btn-block" type="submit" value="¡Buscar!">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    
{% endblock %}

templates/search_results.html.twig
{% extends "base.html.twig" %}
{% block title %}Serach results{% endblock %}

{% block body %}
    <div class="container" id="app">
        <div class="row">
                {% if rooms.count > 0 %}
                    <template v-if="step === 1">
                        <div class="col-12 my-3">
                            <div class="alert alert-info">
                                <h4>A continuación se le muestran las habitaciones disponibles para su búsqueda</h4>
                                <h5><i class="fas fa-dot-circle"></i> Desde el {{from_date|date("d/m/Y")}} hasta el {{to_date|date("d/m/Y")}} ({{num_days}} Día/s)</h5>
                                <h5><i class="fas fa-dot-circle"></i> {{num_persons}} Personas</h5>
                            </div>
                        </div>
                        <div class="col-12 my-3">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Tipo de habitación</th>
                                        <th class="text-right">Habitaciones disponibles</th>
                                        <th class="text-right">Precio/día</th>
                                        <th class="text-right">Precio total de la estancia (incl. imp.)</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for room in rooms %}
                                        <tr>
                                            <td>{{ room.name}}</td>
                                            <td class="text-right">{{ room.getAvailabilityBetweenDates(from_date, to_date) }}</td>
                                            <td class="text-right">{{ room.getPricePerNight | number_format(2, ',', '.')}}€</td>
                                            <td class="text-right">{{ room.getPriceForTotalNights(num_days) | number_format(2, ',', '.')}}€</td>
                                            <td class="text-right">
                                                <button class="btn btn-primary" type="button" @click="selectRoomType({{room.id}},'{{ room.getPriceForTotalNights(num_days) | number_format(2, ',', '.')}}€','{{room.name}}')">
                                                    ¡Reservar YA!
                                                </button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </template>
                    <template v-if="step === 2">
                        {% include "search_partials/booking_form.html.twig" %}
                    </template>                    
                {% else %}
                    <div class="col-12">
                        <div class="alert alert-warning" role="alert">
                            <strong>No hay disponibilidad para las fechas seleccionadas</strong>
                            <a href="/"><h3>Volver a buscar</h3></a>
                        </div>
                    </div>                        
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        var SearchResults = new Vue({
            delimiters: ['${', '}'],
            el: "#app",
            data: {
                step: 1,
                room_type_id: null,
                total_price: "",
                room_name: "",
            },
            methods:{
                selectRoomType: function(room_id, total_price, room_name){
                    this.room_type_id = room_id;
                    this.total_price = total_price;
                    this.room_name = room_name;
                    this.step = 2;
                },
                removeSelection: function(){
                    this.room_type_id = null;
                    this.total_price = "";
                    this.room_name = "";
                    this.step = 1;
                }
            }
        })
    </script>
{% endblock %}